---
- name: Install Apache
  sudo: yes
  apt:
    name: apache2
    state: latest

- name: Install Apache Modules
  apache2_module:
    state: present
    name: "{{ item }}"
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
