---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

# Setup/install tasks.
- include: debian-setup.yml
  when: ansible_os_family == 'Debian'

- include: redhat-setup.yml
  when: ansible_os_family == 'RedHat'

# Configure Apache.
- include: debian-config.yml
  when: ansible_os_family == 'Debian'

- include: redhat-config.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes
