---
# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  shell: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
  changed_when: false
  register: apache_version

- name: Change default apache2.4 site
  sudo: yes
  template:
    src: vhost24.conf.j2
    dest: /etc/httpd/conf.d/default.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1

- name: Change default apache2.2 site
  sudo: yes
  template:
    src: vhost22.conf.j2
    dest: /etc/httpd/conf.d/default.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.2.') != -1
